name: Ubuntu

on: [push]

jobs:
  build:
    strategy:
      matrix:
        # ubuntu 20 doesnt support c++20
        os: [ubuntu-22.04]
    env:
      build_dir: "build"
      config: "Release"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - uses: Jimver/cuda-toolkit@v0.2.23
      id: cuda-toolkit
      with:
        cuda: '12.5.0'

    - name: Configure cmake
      id: configure
      run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}

    - name: Configure Error Processing
      if: ${{ failure() && steps.configure.outcome == 'failure' }}
      working-directory: ${{ env.build_dir }}
      run: |
          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
            echo "---- CMakeFiles/CMakeOutput.log"
            cat CMakeFiles/CMakeOutput.log
            echo "----"
          fi
          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
            echo "---- CMakeFiles/CMakeError.log"
            cat CMakeFiles/CMakeError.log
            echo "----"
          fi
    - name: Build everything else
      working-directory: ${{ env.build_dir }}
      run: cmake --build . --target all --verbose -j `nproc`
