name: arm

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: pguyot/arm-runner-action@v2
      with:
        bind_mount_repository: true
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a53
        image_additional_mb: 512
        commands: |
            sudo apt-get install -y cmake make git
            cd /fq_arithmetic
            mkdir -p cmake-build-release
            mkdir -p cmake-build-debug
            cd cmake-build-debug
            cmake .. -DCMAKE_BUILD_TYPE=Debug
            make -j4
            ctest -C Debug -V  
            cd ../cmake-build-release
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make -j4
            ctest -C Debug -V  
