name: arm

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv6l, armv7l, aarch64]
        include:
#        - arch: armv6l
#          cpu: arm1176
#          base_image: raspios_lite:latest
#          cpu_info: raspberrypi_zero_w
#        - arch: armv7l
#          cpu: cortex-a7
#          base_image: raspios_lite:latest
#          cpu_info: raspberrypi_3b
        - arch: aarch64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: raspberrypi_zero2_w_arm64_w

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: pguyot/arm-runner-action@v2
      with:
        bind_mount_repository: true
        image_additional_mb: 512
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        commands: |
            sudo apt-get install -y cmake make git
            cd /fq_arithmetic
            mkdir -p cmake-build-release
            mkdir -p cmake-build-debug
            cd cmake-build-debug
            cmake .. -DCMAKE_BUILD_TYPE=Debug
            make -j4
            ctest -C Debug -V  
            cd ../cmake-build-release
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make -j4
            ctest -C Debug -V  
